server/entity/Media.ts
The emby format of media urls is <server_url>/web/index.html#!/item?id=xxx..., which is different from Jellyfin's <server_url>/web/index.html#!/details?id=xxx...
This PR add the support of media links for emby servers, via an enviroment variable JELLYFIN_TYPE=emby. It adds a alternative choice, and will not break anything of the current code base.
=> feat: add emby detail url support

src/components/Layout/VersionStatus/index.tsx, src/components/Settings/SettingsAbout/index.tsx
Fix for the jellyseerr version being out of date even though it is up-to-date
**Before fix**
Side-bar
Settings-about page
**After fix**
Side-bar
Settings-about page
Fix for the jellyseerr version being out of date even though it is up-to-date
=> fix: fix for the jellyseerr out of date even though it is up-to-date

src/components/Login/JellyfinLogin.tsx
Relaxes jellyfin url validation so that http://localhost:8096 and http://jellyfin:8096 urls are
accepted in addition to full urls like https://example.com
fix #31
=> fix: relax jellyfin url validation to allow local domains

src/components/UserList/index.tsx
Fixes usertype from appearing as local user even if the mediaServerType is jellyfin
Before
After
=> fix: fix usertype from local user to mediaServerType

.github/workflows/release.yml
adds GITHUB_TOKEN as an env to fix the github_token missing error during release workflow
=> ci: adds GITHUB_TOKEN as an env

src/components/IssueList/IssueItem/index.tsx, src/components/Layout/UserDropdown/index.tsx, src/components/RequestCard/index.tsx, src/components/RequestList/RequestItem/index.tsx
Currently the aspect ratio of profile pictures in dropdown is not being preserved, resulting in pictures looking "squished". Adding `object-fit: cover;` to the image element fixes this ([caniuse.](https://caniuse.com/object-fit)). Please, help me find me another components where there is a profile picture so I can change it there too.
Before:
After:
No prior issue
=> Fix non-square profile pictures being squished

server/routes/auth.ts, server/routes/settings/index.ts, server/routes/user/index.ts
allow avatar url to use externalHostname when setup using local ip
Before
Now
- Fixes #110
=> fix(ui): fix Avatar being broken when setup using internal ip

next.config.js, src/components/IssueDetails/index.tsx, src/components/Login/JellyfinLogin.tsx, src/components/MovieDetails/index.tsx, src/components/Settings/SettingsJellyfin.tsx, src/components/Settings/SettingsLayout.tsx, src/components/Settings/SettingsUsers/index.tsx, src/components/Setup/SetupLogin.tsx, src/components/TvDetails/index.tsx, src/components/UserList/JellyfinImportModal.tsx, src/components/UserList/index.tsx
Adds Play on Emby if the environmental variable is set to Emby
Play on button in media details
Play on button in issue details
User Settings
Settings layout
Jellyfin Settings (now reflects the environmental variable)
Jellyfin Login (now reflects the environmental variable)
UserTypes
1. Plex
2. Jellyfin and Local
3.  Emby and Local
#98
=> feat: conditional media server name to add emby

server/api/jellyfin.ts
Virtual seasons appeared as available / partially available, even though they were not even shown in the Jellyfin web UI. For more info see #119
- Fixes #119
=> fix(scan): ignore virtual seasons

server/api/jellyfin.ts
I have noticed that episodes with virtual location type break things as well, so I have added the filter to all API methods returning JellyfinLibraryItem to not worry in the future.
=>  fix(jellyfin): ignore additional items with virtual location type

src/i18n/locale/ca.json, src/i18n/locale/da.json, src/i18n/locale/de.json, src/i18n/locale/el.json, src/i18n/locale/en.json, src/i18n/locale/es.json, src/i18n/locale/fr.json, src/i18n/locale/hu.json, src/i18n/locale/it.json, src/i18n/locale/ja.json, src/i18n/locale/nb_NO.json, src/i18n/locale/nl.json, src/i18n/locale/pl.json, src/i18n/locale/pt_BR.json, src/i18n/locale/pt_PT.json, src/i18n/locale/ru.json, src/i18n/locale/sq.json, src/i18n/locale/sv.json, src/i18n/locale/zh_Hans.json, src/i18n/locale/zh_Hant.json
fix translation errors for all locales in the import plex user button as it currently shows as
{mediaServerName}
After
Before
=> fix(ui): fix translation errors for all locales in the import plex user button

src/components/Login/index.tsx, src/components/Settings/SettingsJellyfin.tsx
Manual scan in setup used to say "Jellyfin will scan your Jellyfin's server" and same with emby, so
replaced first jellyfin with jellyseerr. And also added emby to login page
=> fix(setup&login): fix a description error in the manual scan in setup and add emby to login page

server/lib/settings.ts
change default email sender name to Jellyseerr on initial setup
=> change email sender name to Jellyseerr on initial setup

.github/workflows/release.yml
Changed run-on to self-hosted to speed up release process
=> Changed run-on to self-hosted to speed up release process

server/index.ts, server/routes/auth.ts
Ensures scheduled jobs are started the first time the server setup.
Also delays starting scheduled jobs until a media server is setup.
N/A
- Fixes #170
=> fix: start scheduled jobs on initial admin account setup

server/entity/Media.ts, server/routes/auth.ts, server/routes/settings/index.ts, server/routes/user/index.ts
The previous PR introduced a new syntax which ignores external jellyfin base path's. I. e. http://localhost:4124/jellyfin.
- Fixes #237
=> Fix jellyfin external url basepath being ignored 

server/api/jellyfin.ts, server/job/jellyfinsync/index.ts
Jellyfin allows combined episodes, like `S01E01-E02`, but seasons containing such episodes are only recognized as `Partially Available`. This PR should fix that by calculating the episode count using `IndexNumberEnd` and `IndexNumber`.
**Example File Name**: `Mr. Robot - S02E01-E02 - eps2.0unm4sk.tc.mkv`
**Before**
**After**
- ~Database migration (if required)~
=> fix: count combined episodes

.prettierignore
When changelog is generated by semantic bot, it keeps failing the prettier format check. So this ignores it
=> chore(prettier): ignore CHANGELOG by prettier

server/job/schedule.ts
This PR disables availability sync temporarily as the current one does not have jellyfin/emby sync ported into it. This would ensure that jellyseerr does not bug out and start removing availability from media despite it being available on jellyfin/emby/*arr as well as their requests.
=> fix: disable availability sync temporarily

server/job/jellyfinsync/index.ts
Multiple repeat notifications being sent for available TV shows everyday at 4.30. Overseerr had [this same issue](https://github.com/sct/overseerr/issues/872) and was fixed in [this commit](https://github.com/sct/overseerr/commit/9b73423d49e1e799cd82764a9ade8c75d92a28a2).
This PR introduces the same changes.
=> fix: multiple notifications for available media

server/api/jellyfin.ts
Use /Library/VirtualFolders Jellyfin API call to fetch Jellyfin libraries, instead of relying on user's view. This allows the admin user to use automatic grouping in Jellyfin
- Fixes #256
=> fix(server/api/jellyfin.ts): use /Library/VirtualFolders Jellyfin API call to fetch Jellyfin libs

src/components/ManageSlideOver/index.tsx
Previously, would cause a 403 error when a non-admin user opened a movie/series page
- Fixes #482
=> Fix permissions on ManageSliderOver

server/interfaces/api/settingsInterfaces.ts, server/lib/settings.ts, src/components/Login/JellyfinLogin.tsx
Implemented dynamic URL generation for the 'Forgot Password' feature. If jellyfin external hostname is set, the URL is generated based on it; otherwise, jellyfin hostname is used as the base URL. The URL includes additional parameters to handle emby support.
- Fixes #199 
- Fixes #424 
- Closes #212
=> fix(jellyfinlogin): use externalHostname if set for forgetpassword link

src/components/Common/ListView/index.tsx
This fix addresses a bug on the Watchlist page where `isAddedToWatchlist` prop was missing. This caused the removal button for watchlist items to be absent. With this fix, `isAddedToWatchlist` prop is re-added and set to `true` so users can now remove items from their local watchlist directly on the Watchlist page.
=> fix(watchlist): added missing prop for watchlist item removal button in watchlist page

tailwind.config.js
This commit addresses a rendering issue with the date picker component. The problem was traced back to a misconfiguration in the tailwindcss settings, resulting in an incorrect width for the popup.
**After:**
**Before:**
- Fixes #415
=> fix: correct width issue in datepicker of filterSliderOver

server/api/jellyfin.ts
All seasons are processed now, but those without any episodes are filtered out again as unavailable. This fixes an issue when jellyfin reports all seasons as virtual.
I've had trouble setting up jellyseerr for my jellyfin instance.
Movies worked fine, but non of my shows were listed as available, even though jellyfin displays them normally.
After digging through the code I found out that jellyfin does indeed report ALL seasons for all my shows as "virtual".
Currently, these seasons are ignored because of this [commit 6574e18](https://github.com/Fallenbagel/jellyseerr/commit/6574e18516201bc11b5f0c422bf6b432c722e067) and this issue #119
How ever, the actual issue seems to not exist anymore as with my changes, virtual seasons get processed, but seasons without any episodes in them are …
=> fix(scan): process virtual seasons if they have non virtual episodes

server/routes/auth.ts
Removes the accidentally added the mediaServerType change code from another feature branch/PR during the auth logic refactor that broke emby logins.
- Fixes #XXXX
=> fix(embyauth): remove the accidentally added mediaServerType 

server/api/jellyfin.ts, server/routes/auth.ts, src/components/Login/JellyfinLogin.tsx, src/i18n/locale/en.json
Solves issue #610 by checking if the first Jellyfin user (at initial set-up) is an admin on Jellyfin or not, as required for set-up.
When logging in with Jellyfin credentials for the initial set-up, this feature additionally checks if the user is an administrator on Jellyfin. If not, it gives an appropriate error. Changes include adding `Policy.IsAdministrator` to the interface `JellyfinUserResponse`, a separate check in authentication for (first user only), and addition of a separate error message in the frontend.
Please note that this is my first ever PR! I am really new to this stuff but am trying to learn, so I sincerely apologize if I made any mistakes or did anything not in accordance to the contribution rules.
- Fixes #610
=> feat: check if first jellyfin user is admin

.github/workflows/conflict_labeler.yml
Before merging the PR you have to manually add the label `merge conflict` 
Put a label `merge conflict` on PR with merge conflict and comment also to say to the maintainer that PR as merge conflict.
Would be simpler to review PR for you (@Fallenbagel) and also gain time cause when merge conflict is detected the maintainer can solve it so you don't have to say to him manually to solve the merge conflict.
=> Add merge conflict labeler workflow

server/lib/notifications/agents/webhook.ts, server/routes/settings/notifications.ts
Switch to using UTF8 encoding instead of ASCII for Webhook bodies. With ASCII, extended characters like emojis will throw errors here, but UTF8 allows encoding anything in the JSON payload.
- Fixes #713
=> fix: use UTF8 encoding for webhook JSON

server/api/jellyfin.ts, server/routes/auth.ts
When a person logs in, their real ip is not sent and the application specified is Axios.
So I added the correct application name and added the X-Forwarded-For header in the axios request headers during login.
=> feat(auth): send real information on login

.github/workflows/snap.yaml
turns off edge snap builds temporarily and makes it manual
=> ci: turn off edge snap builds temporarily

server/routes/auth.ts
Stores jellyfin/emby(?) server name in the settings file. This might come in handy in the future once simultaneous multi-server sync is implemented.
- Fixes #XXXX
=> feat: store jellyfin/emby servername

server/routes/auth.ts
Having a Jellyfin username with capital letters and logging into Jellyseerr with the username in lower case would prevent the auth token to be updated with a new one.
So, instead of comparing the usernames from the input field and the Jellyfin's auth response, we are now comparing the user ID stored in our DB and the one from Jellyfin's auth response.
- Fixes #XXXX
=> fix(auth): case-sensitive logins not updating authtokens

.github/workflows/ci.yml
This is to try and fix formatting issues on #773 on a file that should be ignored.
The reason why the file was ignored was because locally when `yarn format:check` was run, it shows as follows:
However, the format check action is failing saying that the `settings.cypress.json` needs prettier run on it.
- Fixes #XXXX
=> ci: update format check command to ignore .prettierignore files

.github/workflows/ci.yml
Reverts Fallenbagel/jellyseerr#787
#787 was an attempt to figure out why format check was failing on github actions only  for #773 (it passes locally on any machine). It is no longer required as #773 format check is now passing without the need for this.
=> Revert "ci: update format check command to ignore .prettierignore files"

src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx, src/i18n/locale/en.json
Email is mandatory for every user and required during the setup of Jellyseerr, but it is possible to set it empty afterwards in the user settings. When the email is empty, users are not able to connect to Jellyseer. This PR makes the email field mandatory in the user settings.
- Fixes #803
=> fix: empty email in user settings

server/lib/scanners/jellyfin/index.ts
When you have a 4k server setup, and request a 4k item, when it becomes available it also sets the normal item as available thus not allowing the user to request for the normal item
=> fix(jellyfinscanner): assign only 4k available badge for a 4k request instead of both badges

src/components/MovieDetails/index.tsx
After the Media Availability Sync job rund on deleted media, the setting button is still visible even if neither the media file nor the media request no longer exists. This PR hides this button when it's no longer the case
=> fix: remove the settings button of media when useless

package.json, server/index.ts, yarn.lock
Node.js does not respect TTL of DNS entries, resulting in DNS request spam to the DNS server when a lot of API requests are made to external services like TMDB or a Jellyfin server.
This PR adds the [cacheable-lookup](https://github.com/szmarczak/cacheable-lookup) package to fix this issue.
- Fixes #387
- Fixes #657
- Fixes #728
=> fix(api): add DNS caching

.github/workflows/release.yml
Disables snap release builds temporarily until we can fix it.
- Fixes #XXXX
=> ci: temporarily disable snap release builds

server/routes/auth.ts
From #470, validation for ipv6 was sort of broken where for example `::1` was being sent as `1`, therefore, logins were broken. This PR fixes it by using nodejs `net.isIPv4()` & `net.isIPv6` for ipv4 and ipv6 validation.
- Fixes #795 (possibly related)
=> fix(auth): validation of ipv6/ipv4

server/index.ts
This PR aims to address an issue where DNS lookups for 'localhost' were timing out when using `cacheable-lookup` . 'localhost' lookups are now bypassing the cacheable DNS resolution.
- Fixes #XXXX
=> fix: bypass cache-able lookups when resolving localhost

Dockerfile
Running the container, this error shows up `[FATAL tini (7)] exec pnpm failed: No such file or directory`
- Fixes #834
=>  build(dockerfile): add missing pnpm command to dockerfile 

.prettierignore, package.json, pnpm-lock.yaml, server/index.ts
DNS caching was initially implemented to avoid too many DNS requests, as Node.js does not cache them. However, the cacheable-lookup library we used to implement this cache created more problems than it solved, as it caused many unresolved DNS request errors that weren't occurring before.
- Fixes #821
=> fix: remove DNS caching

README.md, package.json, postinstall-win.js
This is a temporary fix for windows baremetal users until we fix #478
- Re #478
=> build(postinstall): postinstall script to downgrade typeorm on windows

Dockerfile
Add postinstall script in Docker before installing dependencies with pnpm so it can be executed at the end of the install.
- Fixes #XXXX
=> fix(docker): add postinstall script

server/lib/availabilitySync.ts
This fix aborts the media availability sync job if the following conditions are met:
- auth token has expired
- connection to jellyfin/emby has been lost
Previously, the sync job will continue even if auth token was invalid or connection was lost, thereby, resulting in removal of series/movies that were never removed on jellyfin/emby/sonarr/radarr. This also removed the requests. With the current fix, the sync job should refuse to run unless the auth token is valid.
supersedes #844 
- Fixes #XXXX
=> fix: abort availability sync job if auth token invalid/connection lost

.github/workflows/docs-deploy.yml
Artifact doesn't need to be downloaded. It's readily available as its the same workflow...
- Fixes #XXXX
=> ci(docs): fix github doc deployment

gen-docs/README.md
Small update to the gen-docs readme.
(This is to trigger github pages deployment)
- Fixes #XXXX
=> docs: update gen-docs readme to trigger gh pages deployment

gen-docs/docusaurus.config.ts
This sets the deployment branch to gh-pages explicitly
- Fixes #XXXX
=> chore(gen-docs): set deploymentBranch for the docs

CONTRIBUTING.md, README.md, gen-docs/README.md
Fixes the formatting of the getting started section so the link is on a new line. In addition adds the proper contributing instructions and fixes the docs url.
- Fixes #XXXX
=> docs(readme): fix issues in readme, contributing guide

docs/extending-jellyseerr/reverse-proxy.mdx, docs/getting-started/aur.mdx, docs/getting-started/buildfromsource.mdx, docs/getting-started/docker.mdx, docs/using-jellyseerr/settings/mediaserver.mdx, docs/using-jellyseerr/users/adding-users.mdx
This add query string support to tabs in docs.
- Fixes #XXXX
=> docs: add querystring support & admonitions to docker page

docs/getting-started/docker.mdx
I had added the podman desktop like steps as docker desktop steps. This pr removes that tab.
Future PR would replace this tab with podman desktop tabs (after verifying the full steps).
- Fixes #XXXX
=> docs: remove docker desktop container creation tab

docs/getting-started/docker.mdx
This removes the code blocks that were added in #863 as it does not look good inside the admonitions.
- Fixes #XXXX
=> docs: remove code block from admonition

src/components/IssueModal/CreateIssueModal/index.tsx
Fix an issue where the user is not able to create an issue because a header is missing in the fetch request.
=> fix: add missing header when creating an issue

src/components/ManageSlideOver/index.tsx
re #841
This simple code fix closes the "manage slide-over" after the user removes the media data from the database or *arr.
- Fixes #841
=> refactor: auto close manage slide on media delete

src/components/Layout/UserWarnings/index.tsx
On my instance, I was getting a frontend error where the were some issues with trying to check the length of undefined.
I tracked it down to a function that was not completely checking its dependencies and just added a more extensive check that should prevent this issue from happening again.
I didn't find anyone else with the same issue but regardless, this PR is a tiny improvement.
This PR does not change any functionality or affect any of the existing ones
N/A
Could not find anyone experiencing the same issue.
=> fix: Length of undefined on users warnings

src/styles/globals.css
Changed the scrollbar to be a thinner and darker to match the theme of jellyseerr.
Before:
After:
- Fixes #856
=> style: implement thin dark scrollbar for better UI consistency

server/routes/auth.ts
Add a missing call to setPassword when an user reset his password for a local Jellyseerr account.
- Fixes #662
=> fix(api): save new password when reset password of local account

src/components/Settings/SettingsJellyfin.tsx
Add missing brackets causing an error when disabling a library in Settings > Jellyfin.
- Fixes #XXXX
=> fix: add missing brackets

src/components/Discover/DiscoverNetwork/index.tsx, src/components/Discover/DiscoverStudio/index.tsx, src/components/MediaSlider/ShowMoreCard/index.tsx
Next.js image component doesn't support protocol-relative URLs, so this PR replaces them to https URLs
- Fixes #XXXX
=> fix: remove protocol-relative URLs from next/image

server/index.ts
This PR removes a custom error handler that sometimes caused issues by sending headers after some content had already been sent.
=> fix(api): fix nextjs error handler

server/index.ts
This PR reverts the nextjs error handler fix that was introduced in #882 as that change requires further refactor which should be held off for another version owing to the fact that there are currently a lot of changes ready for the next version of jellyseerr.
- Fixes #XXXX
=> revert: "fix(api): fix nextjs error handler (#882)"

server/api/externalapi.ts, server/api/jellyfin.ts, server/api/servarr/radarr.ts, server/api/servarr/sonarr.ts, server/lib/notifications/agents/discord.ts, server/lib/notifications/agents/gotify.ts, server/lib/notifications/agents/lunasea.ts, server/lib/notifications/agents/pushbullet.ts, server/lib/notifications/agents/pushover.ts, server/lib/notifications/agents/slack.ts, server/lib/notifications/agents/telegram.ts, server/lib/notifications/agents/webhook.ts, src/components/Login/JellyfinLogin.tsx, src/components/Login/index.tsx, src/components/Settings/SettingsJellyfin.tsx, src/components/UserList/index.tsx
This PR adds missing error handling, such as retrieving the error message in the response, when a Fetch request fails.
- Fixes #XXXX
=> fix: enhance error messages when Fetch API fails

src/components/Discover/DiscoverNetwork/index.tsx, src/components/Discover/DiscoverStudio/index.tsx
This fixes an image size issue in the headers of discover networks and discover studio.
before:
after:
=> fix: resize header image in network and studio pages

server/api/externalapi.ts
This PR fixes the ExternalAPI class where a parameter was missing in the Fetch options.
- Fixes #903
=> fix: add missing parameter to delete requests from ExternalAPI

server/interfaces/api/common.ts, server/interfaces/api/requestInterfaces.ts, server/routes/request.ts, src/components/RequestCard/index.tsx, src/components/RequestList/RequestItem/index.tsx, src/components/RequestModal/MovieRequestModal.tsx, src/components/RequestModal/TvRequestModal.tsx, src/components/RequestModal/index.tsx, src/i18n/locale/en.json
This adds a field with the name of the requested quality profile to the requests page.
The field is filled in the backend via an api call to all configured Radarr/Sonarr instances. If no matching profile can be found, the field is not displayed.
This PR also fixes/alters one backend type, by adding a utility type `NonFunctionProperties`, that removes all function properties of an object, since they don't survive serialization anyway.
- Fixes #816
=> feat: show quality profile on request

docs/getting-started/buildfromsource.mdx
Same thing as #912 but for develop instructions.
- Fixes #XXXX
=> docs(windows): add `win-node-env` instructions to develop build from source

server/api/rating/imdbRadarrProxy.ts
For some new movies, ratings are not yet available on IMDb. This throws this kind of error in the logs: 
```
Error: [IMDB RADARR PROXY API] Failed to retrieve movie ratings: Cannot read properties of null (reading 'Value')
```
This PR removes this unwanted log message.
=> fix(api): handle non-existent ratings on IMDb

server/routes/movie.ts, server/routes/tv.ts
This PR adds a second call to TMDB to retried the overview in English if no overview is available in the requested locale
- Fixes #925
=> fix(tmdb): fallback movie/show overview to English when none is available in requested locale

server/api/externalapi.ts, server/api/jellyfin.ts, server/index.ts, server/lib/availabilitySync.ts, server/lib/scanners/jellyfin/index.ts, server/lib/settings/index.ts, server/lib/settings/migrations/0002_migrate_apitokens.ts, server/lib/settings/migrator.ts, server/routes/auth.ts, server/routes/settings/index.ts, server/routes/user/index.ts, src/components/Settings/SettingsJellyfin.tsx, src/i18n/locale/en.json
This PR changes the way Jellyseerr interacts with Jellyfin. Instead of using auth tokens from an admin user to connect to Jellyfin and perform all its requests, Jellyseerr will now use API tokens.
The API token will be automatically created from the previous auth tokens to ensure a smooth migration.
- Fixes #XXXX
=> feat(jellyfinapi): switch to API tokens instead of auth tokens

server/lib/downloadtracker.ts, src/components/StatusBadge/index.tsx, src/i18n/locale/en.json
When a series is downloaded with a season pack, the status tooltip displays only the name of the first episode as a title, and a list of all episodes as a description, with the same file being repeated for each episode.
This PR fixes this, using the season number as the title and showing only the season pack file currently being downloaded.
Before:
After:
- Fixes #XXXX
=> fix: handle status badge for season packs

src/components/Setup/index.tsx
After setup is finished, the 3rd step of the /setup page was displayed while the homepage was loading.
- Fixes #XXXX
=> fix(setup): page display when homepage is loading

docs/getting-started/nixpkg.mdx, docs/using-jellyseerr/users/editing-users.md
Fix broken documentation anchors. This gave a warning when building docs:
```
Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /getting-started/nixpkg:
-> linking to #overriding-the-package (resolved as: /getting-started/nixpkg#overriding-the-package)
- Broken anchor on source page path = /using-jellyseerr/users/editing-users:
-> linking to /using-jellyseerr/settings/general#discover-region-and-discover-language
```
- Fixes #XXXX
=> docs: fix broken anchors

server/routes/user/index.ts
When importing users from Emby now it sets and displays the correct user type.
- Fixes #948
=> fix: set correct user type when importing from emby

server/constants/error.ts, server/routes/user/usersettings.ts, src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
When the email is modified in the user settings and it is already taken by someone else, a generic message saying that something wrong happened, without saying that it is because the email is already taken by another user. This PR adds this error message for the email.
- Fixes #XXXX
=> fix: add an error message to say when an email is already taken

server/api/servarr/sonarr.ts
This fix changes the behavior of how Overseerr requests series data from Sonarr. Previously, when adding new seasons to a partially available series, Overseerr would initiate a SeriesSearch, causing Sonarr to search for all monitored seasons of the series, including those already available. This behavior is now corrected by executing a MissingEpisodeSearch for the specific seriesId, which results in Sonarr only searching for the seasons that are not already available (including the newly requested seasons).
~~-Translation keys `yarn i18n:extract`~~
~~-Database migration (if required)~~
- Fixes: https://github.com/Fallenbagel/jellyseerr/issues/710
=> fix: change SeriesSearch to MissingEpisodeSearch for season requests

server/index.ts
The time-to-live (TTL) of cookies stored in the database was incorrect because the connect-typeorm library takes a TTL in seconds and not milliseconds, making cookies valid for ~82 years instead of 30 days.
- Fixes #991
=> fix(session): set the correct TTL for the cookie store

server/api/externalapi.ts, server/api/servarr/base.ts, server/lib/downloadtracker.ts
Currently, we sync with sonarr/radarr with whatever value those return. Radarr/Sonarr syncs the activity from the download clients every few minutes. This leads to inaccurate estimated download times, because of the refresh delay with Jellyseerr and the *arrs.
This PR fixes this by making a request to the *arrs to refresh the monitored downloads just before we get these downloads information.
- Re #866
=> feat: refresh monitored downloads before getting queue items

server/entity/Media.ts
Fixes the issue where mediaUrl4K was still using the non-4k mediaId despite having the correct 4k Id stored.
- Fixes #520
=> fix(mediaUrl): use jellyfinMediaId4k for mediaUrl4k

src/pages/_app.tsx, src/utils/fetchOverride.ts
During the migration from Axios to fetch, we overlooked the fact that Axios automatically handled CSRF tokens, while fetch does not. When CSRF protection was turned on, requests were failing with an
"invalid CSRF token" error for users accessing the app even via HTTPS. This PR overrides fetch to ensure that the CSRF token is included in all requests.
@M0NsTeRRR thanks for helping me debug and find a solution!
- Fixes #1011
=> fix(csrf): override fetch to handle requests with CSRF token

server/api/rating/rottentomatoes.ts
This fixes a bug where some media don't have any rottentomatoes ratings.
- Fixes #XXXX
=> fix: handle non-existent rottentomatoes rating

server/routes/auth.ts, server/routes/avatarproxy.ts, server/routes/settings/index.ts, server/routes/user/index.ts, src/components/Blacklist/index.tsx, src/components/CollectionDetails/index.tsx, src/components/Common/CachedImage/index.tsx, src/components/Common/ImageFader/index.tsx, src/components/Common/Modal/index.tsx, src/components/CompanyCard/index.tsx, src/components/GenreCard/index.tsx, src/components/IssueDetails/IssueComment/index.tsx, src/components/IssueDetails/index.tsx, src/components/IssueList/IssueItem/index.tsx, src/components/Layout/UserDropdown/index.tsx, src/components/ManageSlideOver/index.tsx, src/components/MovieDetails/index.tsx, src/components/PersonCard/index.tsx, src/components/PersonDetails/index.tsx, src/components/RequestCard/index.tsx, src/components/RequestList/RequestItem/index.tsx, src/components/RequestModal/AdvancedRequester/index.tsx, src/components/RequestModal/CollectionRequestModal.tsx, src/components/Selector/index.tsx, src/components/TitleCard/index.tsx, src/components/TvDetails/index.tsx, src/components/UserList/JellyfinImportModal.tsx, src/components/UserList/index.tsx, src/components/UserProfile/ProfileHeader/index.tsx
Avatar proxy was allowing every request to be proxied, no matter the original ressource's origin or filetype. This PR fixes it be allowing only relevant resources to be cached, i.e. Jellyfin/Emby images and TMDB images.
- Fixes #1012
- Fixes #1013
- Fixes #1017
=> fix: rewrite avatarproxy and CachedImage

docs/getting-started/buildfromsource.mdx
Removes the tabs about latest/develop. Deprecate yarn. Replaced by pnpm 9.0. And nodejs 20 LTS version.
Supersedes #996 
- Re #1020
=> docs(buildfromsource): remove latest/develop tabs and update instructions to support 2.0.0

src/components/RequestList/RequestItem/index.tsx
This fixes an issue where when the request is modified it was showing the avatar of the requester instead of the modifiedBy user
- Fixes #1017
=> fix(request-list): wrong avatar rendered for the modifiedBy user in request list

server/lib/settings/index.ts, server/lib/settings/migrator.ts
Exit Jellyseerr if the migration fails because of a configuration error.
- Fixes #XXXX
=> feat: exit Jellyseerr when migration fails

.gitignore, server/lib/settings/migrator.ts
=> feat: add more logs to migrations and create a settings backup

server/routes/service.ts, server/routes/settings/sonarr.ts, src/components/Settings/SonarrModal/index.tsx
Currently, the language profiles removed with Sonarr v4 are still available for compatibility reasons. However, Jellyseerr still queries and displays language profiles (marking them as “Deprecated”). This PR hides and does not query language profiles unless Sonarr v3 is used.
- Fixes #207
=> fix: remove language profiles dropdown for Sonarr v4

server/api/externalapi.ts
This PR adds extraction of basic authentication credentials from the URL and then pass the credentials as the `Authorization` header. And then credentials are removed from the URL before being passed to fetch. This is done because fetch request cannot be constructed using a URL with credentials.
I have not tested whether the basic authentication works though. Will create a preview called `:preview-fix-basic-auth`
- Fixes #1027
=> fix(externalapi): extract basic auth and pass it through header

src/components/Login/JellyfinLogin.tsx
Add a missing validation to ensure that the baseUrl starts with a slash.
=> fix(setup): add leading slash validation for baseUrl

src/i18n/extractMessages.ts
This PR fix a bug when a translation message has two single quote like `{"message": "hello 'world'"}`, the extractMessages function was escaping the message correctly.
=> fix(i18n): update extractMessages function for better escaping of characters

overseerr-api.yml, server/entity/Blacklist.ts, server/entity/Media.ts, server/routes/blacklist.ts, src/components/BlacklistBlock/index.tsx, src/components/BlacklistModal/index.tsx, src/components/ManageSlideOver/index.tsx
For admin users, the button to blacklist a media (used on every media card) was displaying a Modal, that was requesting data BEFORE the modal was displayed. This resulted in dozens of additional requests everytime media cards were displayed.
A useless ratelimit has also been removed on the blacklist endpoint.
Joins between the Media table and the Blacklist table will be lazy loaded instead of being eager loaded.
=> fix(blacklist): request data only when modal is shown, remove useless ratelimit and lazy load blacklist

docs/extending-jellyseerr/reverse-proxy.mdx
Fix posters not showing up when using sub-folder (at least with NPM)
Fixes title card images not appearing if using subfolders.
Before:
After:
I know this is not officially supported but I figured this was a byproduct of the recent update and it just wasn't thought about. Small change but for idiots like me it'll save 10-100~ mins of trying to troubleshoot 😅.
=> docs: added missing sub_filters in nginx subpath

src/components/Settings/RadarrModal/index.tsx, src/components/Settings/SettingsJellyfin.tsx, src/components/Settings/SettingsMain/index.tsx, src/components/Settings/SettingsPlex.tsx, src/components/Settings/SonarrModal/index.tsx
Default URL validation from the Yup module doesn't allow URLs like "http://custom-host", while it is a correct value for an external URL.
- Fixes #1068
=> fix: use less strict validation for external URLs

src/components/Selector/index.tsx
The size of streaming service logos has been changed due to the Next.js Image component update.
- Fixes #1103
=> fix(ui): resize streaming service logos

server/lib/settings/index.ts
When writing the settings.json file ensure that the file is fully written by writing it to temporary file before renaming it to the final settings path. This should prevent issues where the config gets lost due to the file being corrupted.
When running in K8S both Jellyseerr and Overseerr have suffered from losing the config due to pod restarts, this change makes it so that the settings.json is first wirtten to a temporary file then it is renamed to its final name. This should help prevent cases where a partial or unflushed write cause the loss of the whole settings.
=> fix(server/settings): write settings to a temp file then move

server/routes/avatarproxy.ts
Refactoring avatarproxy to retrieve avatars from the Jellyfin API instead of the public endpoint broke Emby avatars that doesn't have this API method.
- Fixes #1101
=> fix(avatarproxy): add support for Emby avatars

docs/troubleshooting.mdx
This troubleshooting page explains how to solve dns blockage issues from ISPs and how to fix some slowdowns / ipv6 errors with the forceIpv4First environment variable.
- Fixes #1098
=> docs: add a troubleshooting page

src/components/Common/ButtonWithDropdown/index.tsx, src/components/Common/PlayButton/index.tsx
Previously, the "Play on Jellyfin" or "Watch Trailers" buttons used the onClick event and window.open to open links, instead of using 'a' elements with a href.
- Fixes #XXXX
=> fix: use links instead of buttons for external links in movie/tv details page

server/lib/scanners/jellyfin/index.ts
This PR changes the order of the metadata provider to TMDB first and then fallback to TheTVDB if no TMDB metadata is available. Previously, TheTVDB was used first and there was no fallback if the latter failed.
- Fixes #1137
=> fix: use tmdb first as metadata provider and fallback to tvdb

server/routes/request.ts
If Jellyseerr can't connect to Radarr/Sonarr, the "Recent Requests" slider will not load because of the error throwed when trying to get the Quality Profile. This PR catch this error so the recent requests are well displayed.
=> fix(discover): display recent requests even if there is an error with *arr

server/interfaces/api/discoverInterfaces.ts, server/routes/discover.ts, server/routes/user/index.ts
This issue introduced by #708 was breaking the build of the app. An `id` property was missing.
=> fix(discover): resolve a typing issue with the WatchlistItem interface

server/api/externalapi.ts
An issue with undici throwing an error because the response body was not decompressed properly: https://github.com/nodejs/undici/issues/3762
```
TypeError: terminated
at Fetch.onAborted (node:internal/deps/undici/undici:10916:53)
at Fetch.emit (node:events:518:28)
at Fetch.emit (node:domain:488:12)
at Fetch.terminate (node:internal/deps/undici/undici:10102:14)
at Fetch.fetchParams.controller.resume (node:internal/deps/undici/undici:10893:36)
at processTicksAndRejections (node:internal/process/task_queues:95:5) {
[cause]: Error: incorrect header check
at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
errno: -3,
code: 'Z_DATA_ERROR'
}
}
```
This PR forces the Accept-Encoding header to gzip without deflate for Emby.
This undici issue been fixed in undici 6.21, which is only available …
=> fix(emby): change default value of Accept-Encoding header

server/api/rating/rottentomatoes.ts
This fixes a bug where some movies don't have any rottentomatoes ratings, which causes ratings from other services to not show
Before this change:
After this change:
- Fixes #1168
=> fix: Handle non-existent rottentomatoes rating for movies

docs/getting-started/buildfromsource.mdx
Changed instructions that said to checkout to develop branch. Also removed `JELLYFIN_TYPE`
=> docs(buildfromsource): remove references to develop

overseerr-api.yml, src/components/RequestList/index.tsx
The Sort Direction was loaded with values from the localStorage, but `undefined` was assigned if no previous Sort Direction existed, causing the client to send undefined as a string for the Sort Direction.
- Fixes #1147
=> fix(requestlist): use default value of sort direction only if valid

overseerr-api.yml
The OpenAPI spec had the wrong parameter name, which was fixed in this PR.
- Fixes #1161
=> docs: change the OpenAPI parameter for jellyfinUserIds

src/components/MovieDetails/index.tsx
The frontend was coercing the zero value to false.
Before:
After:
- Fixes #1166
=> fix(ui): display Rotten Tomatoes for 0% ratings

src/components/Discover/DiscoverTvUpcoming.tsx, src/i18n/locale/en.json, src/utils/defineMessages.ts
Add better types to our custom `defineMessages` implementation replacing the one from `react-intl`.
The returned object will now be typed with the keys coming from the input of the `defineMessages`, to better intercept some mistakes with i18n messages.
=> refactor(i18n): add better types to our custom defineMessages

server/entity/MediaRequest.ts
- This will fetch the proper sonarr/radarr specific override rule to apply.
- This will skip override rules for anime TV shows unless the `overrideRule` explicitly includes the anime keyword.
- Apply the most specific override rule first (e.g., rules with multiple conditions like `genre`, `language`, and `keywords`)
- Debug logs for override rules
- Fixes #XXXX
=> fix: properly fetch sonarr/radarr specific override rules

src/components/Settings/SettingsMain/index.tsx
When the streaming region is set to another value than the default one, the setting starts toggling itself from the default value to the new value and vice-versa constantly
- Fixes #1200
=> fix(usersettings): fix the streaming region setting toggling itself

src/components/Settings/SettingsMain/index.tsx
The streaming region selection field is always in the foreground and overlaps other open dropdowns.
Before:
After:
- Fixes #1206
=> fix(ui): resolve streaming region dropdown overlap

server/routes/user/index.ts
Fixes an infinite loading issue on the users page caused by incompatible request count query syntax with certain PostgreSQL configurations. The issue manifested as a "column requestcount does not exist" error when sorting users by request count.
- Fixes #XXXX
=> fix(users): correct request count query for PostgreSQL compatibility

server/entity/MediaRequest.ts
When a series is requested, an event is triggered by TypeORM after the request status has been updated. The function executed by this event updated the request status to "PROCESSING", even if the request already had this status. This triggered the same function once again, which repeated the update, in an endless loop.
=> fix: prevent TypeORM subscribers from calling itself over and over

server/constants/error.ts, server/routes/auth.ts, src/components/Login/JellyfinLogin.tsx
This PR adds an error message when the database has no admin user and Jellyseerr has already been set up (i.e. settings.json is filled in), instead of having a generic error message.
Before:
After:
=> fix(jellyfinlogin): add proper error message when no admin user exists

server/api/externalapi.ts, server/api/servarr/radarr.ts, server/api/servarr/sonarr.ts, server/entity/MediaRequest.ts
This PR clears the Radarr/Sonarr cache after a request has been made, because the media status on Radarr/Sonarr will no longer be good. It also resolves a bug that prevented the media from being deleted after a request had been sent to Radarr/Sonarr.
- Fixes #1207
=> fix(externalapi): clear cache after a request is made

src/components/Setup/index.tsx, src/i18n/locale/en.json
This pr resolves an issue where the continue button in setup step 3 remained disabled after a page refresh even when libraries are toggled. This was happening because `mediaServerSettingsComplete` state was reset on refresh and not correctly re-initialized.
- The state is properly initialized from localStorage when the component mounts.
- Validation for enabled libraries is done when the state is hydrated so the continue button state is correct
- The continue button remains enabled if a library has already been toggled.
**Previously** (there is a library enabled after refresh but continue button disabled until i re-toggle):
After this PR the continue button will always stay enabled if there is a library setup. 
- Fixes #XXXX
=> fix(setup): fix continue button disabled on refresh in setup 3

src/components/MovieDetails/index.tsx, src/components/TvDetails/index.tsx
Fix an issue introduced by #932, because CachedImage now requires to have a type (tmdb or avatar)
=> fix: specify cached image type

overseerr-api.yml
While building an API client using openapi-generator-cli, I encountered an issue in overseerr-api.yml. The PUT /overrideRule/{ruleId} operation was missing a parameter definition, which I have now added.
I am not sure how Swagger UI is built or if it needs to be updated as well. Please advise if further changes are required.
I did not perform a build, as I believe it is unnecessary for this small fix. If building is required, please let me know.
=> fix: Add missing parameter definition for PUT /overrideRule/{ruleId} in API spec

server/api/externalapi.ts
This PR addresses an issue introduced with #840 where cached responses for PlexTV API requests returned incorrect user data when multiple users were logged in (when previous cache existed). This was caused by a shared cache key that did not account for differences in auth tokens, i.e `X-Plex-Token`. The `serializeCacheKey` method should now include headers in the cache key generation to ensure unique cache keys. This should fix the plex user mismatch that occurred due to the same cache key being used without accounting for the difference in auth token.
**_(Note)_**
_The reason this did not occur on axios was because it was creating a new axios instance in the constructor with its own base config for each user/token, while with fetch it was reusing the same instance with shared cache._
PR …
=> fix: resolve plex user mismatch due to caching issues

src/components/Settings/SettingsLogs/index.tsx
This should make sure that the ui doesnt break for users who has long appDataPaths
- Fixes #XXXX
=> style(logs): apply break-words for appDataPath

src/components/Settings/RadarrModal/index.tsx, src/components/Settings/SonarrModal/index.tsx
This should fix the override rule tile for mobile
**Previously:**
**After:**
- Fixes #XXXX
=> style(overriderules): optimises the override rules tile for mobile

server/lib/settings/migrations/0004_migrate_region_setting.ts
Adds a guard clause to skip region migration if discoverRegion and streamingRegion properties already exist in settings. This prevents accidental overwrites of existing region settings during multiple runs and ensures the migration only executes when needed.
Previously, the migration would run every time regardless of whether the new region properties existed, potentially overwriting user preferences.
- Fixes #1251
=> fix(settingsmigrator): prevent region migration from running multiple  times

server/api/themoviedb/index.ts
This change is done to adhere with the TMDB rule of having one apikey per app and since jellyseerr has diverged from overseerr, it is best practice to use our own apikey so that TMDB can properly identify any issues that could be caused by jellyseerr
- Fixes #XXXX
=> refactor(tmdb): replace apikey

src/components/Settings/RadarrModal/index.tsx, src/components/Settings/SonarrModal/index.tsx
If you setup an override rule on a service that is not created yet, the override rule doesn't get added to the service because it has no ID, but a record for that override rule is nonetheless created. This PR allows override rules only when the service is setup.
=> fix(overriderules): allow override rules only when the service is created

.github/workflows/ci.yml
This is an attempt to utilise the [linux arm64 hosted runners](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/) which should reduce the build times significantly. In addition, this should leverage the github's built-in caching.
The PR for releases to utilise the aforementioned runner would follow this one.
- Fixes #XXXX
=> ci: utilise the linux arm64 hosted runners

.github/workflows/ci.yml
This is another attempt to get arm64 runner working by upgrading the runner to `ubuntu-24-04`, hoping it works better.
Related to #1275
- Fixes #XXXX
=> ci: upgrade runner to ubuntu 24.04 to get arm64 runner working

.github/workflows/ci.yml
The issue was all because of using the wrong label. 18 hours wasted waiting for a non-existent runner to start. It is `ubuntu-24.04-arm`
https://github.com/orgs/community/discussions/148648#discussion-7793082
- Fixes #XXXX
=> ci: correct arm runner label

.github/workflows/ci.yml
This is done as github actions doesnt support inline replacement that was done on #1279
- Fixes #XXXX
=> ci: seperate job to pass in sanitised platform

.github/workflows/ci.yml
This pr fixes a typo made when sanitising the platform name in #1280 
- Fixes #XXXX
=> ci: fix typo when sanitising platform

.github/workflows/ci.yml
This PR fixes sanitation typo when passing to github env. This also adds the sanitation step to test so that we can test it before merging this pr. That part will be removed after testing.
- Fixes #XXXX
=> ci: fix typo when passing sanitised platform to github env

.github/workflows/ci.yml
This is an attempt to utilise the `push-by-digest` feature to push the individual architecture's digest into docker registry without tagging it and then combining those digests to create one multi-arch `develop` tag.
Reference: https://andrewlock.net/combining-multiple-docker-images-into-a-multi-arch-image/
- Fixes #XXXX
=> ci: push individual arch digest only and merge from digest

src/components/Setup/index.tsx
This PR fixes a bug where the validation error message is displayed over and over because of a React useEffect dependency issue. Previously, the `validateLibraries()` function was being called inside a useEffect that depended on a state that this function was updating.
=> fix(setup): resolve looping library validation error message

server/job/schedule.ts
Due to merging issues with upstream, some jobs for the Plex media server where also running on Jellyfin/Emby instances. This PR makes them run only when the media server is Plex.
- Fixes #1329
=> fix(jobs): run plex/jellyfin jobs only for the relevant media server

src/components/UserList/BulkEditModal.tsx
This PR fixes a bug where admin users could edit the permissions of other admins in the bulk edit modal.
- Fixes #1309
=> fix: disallow admins to edit other admins in bulk edit

server/entity/User.ts, server/routes/auth.ts
By default, the jellyfinAuthToken of every user was always retrieved from the database, and sometimes sent back to the client. Any logged-in user could retrieve this token via a request containing admin user information, and use it to gain full access to Jellyfin. This PR removes the auth token and the device ID from the fields selected by default by TypeORM.
=> fix: resolve a vulnerability with admin token

next.config.js
This updates `next.config.js` to allow images from `plex.tv` in Next.js' built-in image optimization (`next/image`).
Previously, attempts to load Plex users' avatar during import resulted in a `400 Bad Request` error (`"url" parameter is not allowed`), as the domain was not explicitly whitelisted.
=> fix: missing plex.tv url in images remotePatterns

Dockerfile, Dockerfile.local
pnpm latest version is now v10. We still use v9, and the latest version of pnpm was used in Dockerfile instead of v9.
=> ci: set the pnpm version number explicitly

server/utils/customProxyAgent.ts
The Node.js [documentation](https://nodejs.org/dist/latest-v22.x/docs/api/http.html#httpglobalagent) mentions that the default keep-alive value is not used when creating a global agent manually, which is done in `server/customProxyAgent.ts`.
- Re #1365
=> fix: assign the keep-alive value explicitly

src/components/MediaSlider/index.tsx, src/hooks/useDiscover.ts
By default, useSWRInfinite revalidates the first page every time a new page is loaded, resulting in additional requests being sent. This PR disables this behavior.
- Fixes #1380
=> fix: disable first page revalidation in useSWRInfinite

src/components/ManageSlideOver/index.tsx, src/components/RequestList/RequestItem/index.tsx
Fix the "Remove From *arr" button in the slideover of the movie/series details page. The issue was caused by an attempt to delete a file that didn't exist.
=> fix: fix remove from *arr in item details

server/routes/user/usersettings.ts, src/components/UserList/index.tsx, src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
Because of a misunderstanding, the requirement to have a mandatory email for local users was removed, when it shouldn't have been.
- Related to #900
- Fixes #1367
=> fix: add email requirement for local users

server/routes/settings/index.ts
This PR fixes a bug where the error message when no library exists was not displayed because of a Jellyfin-specific check failing with Emby.
=> fix(emby): throw the right error message if no library exists

src/components/Settings/SettingsServices.tsx
This PR disable the 'New Override Rule' button when no Radarr/Sonarr service exists.
=> fix(overriderules): enable override rules only when a service exists

.github/workflows/cypress.yml, cypress.config.ts, next-env.d.ts, package.json, pnpm-lock.yaml, server/index.ts, server/lib/email/index.ts, src/utils/fetchOverride.ts, tsconfig.json
This PR updates some dependencies and adds overrides to mitigate vulnerabilities.
It also replaces `csurf` with `csrf-csrf` as `csurf` is now deprecated
- Re #783
=> chore: update dependencies

jellyseerr-api.yml, server/routes/user/index.ts, src/components/Selector/index.tsx, src/components/Settings/OverrideRule/OverrideRuleTiles.tsx
* Updates /users API to allow efficient retrieving of multiple users at once.
* Uses this API to ensure that all users selected in an overridden rule are selected.
- Fixes #1332
=> fix(overriderules): allows every user to be added to the override rules

server/routes/user/index.ts
PostgreSQL requires that the ORDER BY expression must appear in the SELECT list when using DISTINCT. Since we were using a computed expression in the ORDER BY clause, we need to include it in the SELECT list as well.
- Re #1333
=> fix(users): correct user list for Postgres

src/components/MovieDetails/index.tsx, src/components/TvDetails/index.tsx
This PR fixes an UI issue with inconsistent size for media action icons.
Before:
After:
- Fixes #1440
=> fix(ui): correct media action icon size

docs/getting-started/buildfromsource.mdx
The current steps for installing Jellyseerr as a service with NSSM do not work, since the 'AppDirectory' parameter defaults to the Node.js directory. The [] brackets have to be removed as well.
=> docs: update steps for service installation with NSSM

package.json, pnpm-lock.yaml, server/index.ts, server/types/custom.d.ts, src/utils/fetchOverride.ts
This reverts csrf-csrf change brought on by [9e3119](https://github.com/fallenbagel/jellyseerr/pull/1393/commits/9e3119850dac9d772de8a0a5a9377433d892de83) in #1393 back to `csurf` that is [maintained](https://www.npmjs.com/package/@dr.pogodin/csurf)
can be tested with `preview-csrf-protection-fix`
- Fixes #1441
=> revert: reverts csrf-csrf back to csurf

server/utils/customProxyAgent.ts
With the update of undici to v7, the bypass list of addresses (no_proxy addresses) was not ignored anymore.
- Fixes #1454
=> fix(proxy): update http proxy to accept bypass list with undici v7

src/components/RequestList/RequestItem/index.tsx, src/components/RequestList/index.tsx
This PR hide the "Remove from *arr" button in the request list when the service of the request doesn't exist anymore.
- Fixes #1449
=> fix(requestlist): hide the remove from *arr button when no service exists

src/components/TitleCard/index.tsx
The PR #1398 introduced an issue where the blacklist button was not visible anymore on the TitleCards for Plex. This PR fixes it.
=> fix(blacklist): add back the blacklist button on TitleCard for Plex

src/components/MovieDetails/index.tsx, src/components/TvDetails/index.tsx
Fix a z-index issue with the "Watch Trailer" button being under the "Request in 4k" button
Before:
After:
- Fixes #1462
=> fix(ui): move watch trailer button above the 4k request button

src/components/Settings/Notifications/NotificationsEmail.tsx
The SMTP test functionality was not working when using self-signed certificates due to the missing `allowSelfSigned` option in the request body.
This commit ensures that `allowSelfSigned: values.allowSelfSigned` is properly included, allowing self-signed certificates when enabled in the settings.
- Fixes #1374
=> fix(smtp-notification-test): missing allowSelfSigned option in test function

src/components/AirDateBadge/index.tsx
This reverts #1390 as it created more confusion when we offsetted the air date in relevance to the timezone. It also changes the relative time to use date instead of time (so it will say `aired yesterday` `today` `5 days ago` instead of `aired x hours ago` since we dont really the airtime data.
- Fixes #XXXX
=> revert(airdate): reverts airdate offset & changes relative time to only display date (not time)

server/routes/media.ts
This PR add a check to verify if the item to be deleted inside the *arr service still exists before actually sending the delete request.
=> fix: check if the file still exists in the service before deleting

src/components/RequestModal/TvRequestModal.tsx
This PR corrects the order of the seasons displayed on the request card, because it was not always ordered.
Before:
After:
=> fix(ui): correct seasons badge order

src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
The discover language selection field is always in the foreground and overlaps other open dropdowns.
- Fixes #1475
=> fix(ui): resolve discover language dropdown overlap

package.json, pnpm-lock.yaml
This updates nextjs to fix a security vulnerability.
- Fixes #1516
=> chore: update nextjs to 14.2.25 (CVSS 9.1 vulnerability fix)

docs/getting-started/docker.mdx
Switch to ghcr.io instead of dockerhub in the doc for helm
Reason : https://docs.docker.com/docker-hub/usage/
=> docs(helm): use ghcr.io registry instead of dockerhub

server/api/servarr/radarr.ts, server/lib/availabilitySync.ts
This PR fixes a bug where the avaibility sync job was not removing properly 4k items when the same Radarr server was used for both non-4k and 4k media.
=> fix(job): handle media removal for 4k on the same server

server/api/externalapi.ts, server/api/servarr/radarr.ts, server/api/servarr/sonarr.ts, server/interfaces/api/requestInterfaces.ts, server/routes/media.ts, server/routes/request.ts, src/components/RequestList/RequestItem/index.tsx, src/components/RequestList/index.tsx
This PR fixes the "Delete from *arr" button in the request list.
- It checks from the API whether the *arr server corresponding to the request still exists before displaying the remove button.
- It fixes a cache removal issue that could cause problems when deleting recently added media.
- It also reverts #1476 which introduced problems during removal.
- Fixes #1494
=> fix: correct "Remove from *arr" button

server/lib/scanners/jellyfin/index.ts
Some logs for the Jellyfin scanners were labelled 'Plex Sync' instead of 'Jellyfin Sync', leading to confusion
=> fix(job): rename Plex Sync to Jellyfin Sync

server/lib/notifications/agents/gotify.ts
- Now uses markdown line-breaks instead of relying _purely_ on newlines (which wasn't working previously).
- Now uses markdown formatting to clean the output up a bit.
- `displayUrl` now applies an ellipsis if the URL is longer than 40 characters.
- `displayUrl` formatting _slightly_ changed to match the others.
**Previous Output**
**Changed Output**
=> feat(gotify): use markdown linebreaks instead of relying purely on newlines

next.config.js, src/components/TvDetails/Season/index.tsx
This fixes an issue where episode images get `url parameter not allowed` when accessing the episode images.
Before:
Now:
It actually works
- Fixes #XXXX
=> Fix episode images url not allowed

server/lib/imageproxy.ts
This fixes a regression caused by #1520 which broke the file extension detection thereby breaking avatars. 
Previously, the image caching code derived the file extension using the URL (by splitting on a dot). This worked correctly when using the native fetch API, as the URLs contained proper extensions. However, when switching to axios, some image URLs (especially ones with query parameters) no longer produced a valid extension. For example, URLs for avatar images started returning parts like "com:443/UserImage?UserId=…" as the extension, causing cache file paths to be invalid (leading to ENOENT errors when reading or writing files).
- Fixes #XXXX
=> fix(imagecache): fix avatar cache folder creation

charts/jellyseerr-chart/Chart.yaml, charts/jellyseerr-chart/README.md, charts/jellyseerr-chart/templates/deployment.yaml, charts/jellyseerr-chart/values.yaml
Allow to configure liveness/readiness probes + Add optional startup probe
Additional comment fixes on values.yaml so autostyle is properly working
- Fixes #XXXX
=> feat: make chart probes configurable

src/components/Settings/Notifications/NotificationsPushover/index.tsx
the sound setting will now be stored correctly
fix #1614
- Fixes #1614
=> fix(pushover notificatons): the sound setting will now be stored correctly

docs/getting-started/docker.mdx, server/routes/auth.ts
This PR removes some remaining mentions of `JELLYFIN_TYPE`, removed in #685
=> docs: remove obsolete JELLYFIN_TYPE mentions

src/hooks/useDiscover.ts
Fixes a crash on the `/discover/watchlist` page that occurred when the number of items was exactly a multiple of the page size (e.g., 80, 100, 120). The issue was caused by incorrect end-of-pagination detection, leading to infinite data fetching. This update adjusts the `isReachingEnd` condition to correctly handle these edge cases by checking if `totalResults` is less than or equal to the expected total based on `size * pageSize`.
- Fixes #1623
=> fix(usediscover hook): detect end of pagination when totalSize is a multiple of pageSize

src/components/Settings/Notifications/NotificationsGotify/index.tsx, src/components/Settings/Notifications/NotificationsNtfy/index.tsx, src/components/Settings/Notifications/NotificationsWebhook/index.tsx, src/components/Settings/RadarrModal/index.tsx, src/components/Settings/SettingsJellyfin.tsx, src/components/Settings/SettingsMain/index.tsx, src/components/Settings/SettingsPlex.tsx, src/components/Settings/SonarrModal/index.tsx, src/utils/urlValidationHelper.ts
Replaced regex-based URL validation with the native JavaScript URL constructor to improve reliability. This approach should be more robust and should help prevent bugs like the one we previously encountered with malformed regex.
- Fixes #1539
=> refactor(url validation): replace regex-based URL validation by the JavaScript URL constructor

src/utils/urlValidationHelper.ts
The `isValidURL` function was returning `false` when the provided value was undefined/null/empty, but needs to return `true` instead so it doesn't interfere with Yup validation.
=> fix(url validation): correct URL validation for empty fields

server/routes/imageproxy.ts, src/components/Common/CachedImage/index.tsx, src/components/RequestModal/SearchByNameModal/index.tsx
This PR adds image caching using CachedImage for TVDB images, appearing in the SearchByName modal (displayed when a mismatch between TMDB and TVDB happens).
=> feat: add image caching for TVDB

src/components/Discover/DiscoverNetwork/index.tsx, src/components/Discover/DiscoverStudio/index.tsx, src/components/MediaSlider/ShowMoreCard/index.tsx
This PR replaces some Images with CachedImage for missing TMDB-related images.
=> fix: add missing cache for some tmdb images

docs/getting-started/docker.mdx
One of the previous prs changed it to ghcr.io. While we do support it, that's our secondary and dockerhub has always been our primary.
- Fixes #XXXX
=> docs: revert image change to dockerhub.io

server/api/externalapi.ts, server/api/jellyfin.ts, server/routes/auth.ts
Currently, when users log out of Jellyseerr (or simply close their browser), their Jellyfin "Device" entries remain active on the Jellyfin server under the name "Jellyseerr."
This means old sessions pile up.
And this can lead to issues when users have a limited number of allowed simultaneous sessions in Jellyfin (e.g., 5 sessions per user), as each new Jellyseerr login creates a new session without cleaning up the old ones.
- Fixes #1572
=> fix(jellyfin): clean up Jellyfin sessions on Jellyseerr logout

src/components/PersonDetails/index.tsx
This PR fixes the media type filter on mobile
Before:
After:
=> fix(ui): make person media type filter consistent on mobile

src/components/IssueDetails/IssueComment/index.tsx
The IssueComment module was not displaying markdown list's ordered or unorderd.  Removing the allowed elements so all markdowns are allowed seems to fix this issue and work similar to github's comment  control with lists and markdown.
fix #1328
- Fixes #1328
=> fix(issuecomment): fix issue display lists in IssueComment

server/routes/user/usersettings.ts
This update modifies the user settings endpoint so that, when validating email uniqueness, the query excludes the current user’s own record. As a result, clearing or changing an email no longer triggers a false “InvalidEmail” error. Only genuinely conflicting emails on other users will be rejected.
- Fixes #XXXX
=> fix(usersettings): exclude current user when checking for existing email

src/components/Settings/SettingsMain/index.tsx
This PR adds a tip explaining what is the purpose of the new 'Youtube URL' setting.
=> fix(settings): add a tip for youtube URL setting

src/components/Settings/Notifications/NotificationsNtfy/index.tsx
When using the username/password as auth method, the saved value was not displayed properly because
of a wrong property name introduced by a missing type.
- Re #1705
=> fix: correct typing issue

server/lib/notifications/agents/gotify.ts
This PR fixes an issue where Gotify notifications would not be sent when the priority was configured to 0.
- Fixes #1754
=> fix(gotify): notifications blocked when priority set to 0

package.json, pnpm-lock.yaml
Axios attempts to resolve IPv6 hostnames, see the issue on GitHub: https://github.com/axios/axios/issues/5333.
This problem affects Axios versions below 1.7.7.
- Linked to (partially) #1747
=> chore(deps): upgrade axios to support ipv6

src/components/Settings/Notifications/NotificationsEmail.tsx, src/components/Settings/RadarrModal/index.tsx, src/components/Settings/SettingsJellyfin.tsx, src/components/Settings/SettingsPlex.tsx, src/components/Settings/SonarrModal/index.tsx, src/components/Setup/JellyfinSetup.tsx, src/i18n/locale/en.json
Remove validation on the hostname field as it's really challenging to create a valid regex for IPv4/IPv6/hostname. We already validate that the configuration is correct for Radarr/Sonarr, etc., before allowing users to save. For notifications, users have a test button, and I think that is sufficient for now.
- Fixes #1747
=> fix: allow setting an IPv6 address in the hostname field

server/routes/imageproxy.ts
The ImageProxy for TMDB and TheTVDB were initialized before the proxy settings were set up, so they were ignoring the proxy settings.
- Fixes #1787
=> fix(proxy): initialize image proxies after the proxy is set up

jellyseerr-api.yml
This PR adds new fields to the UserSettings schema, including username, email, discordId, and various quota limits for movies and TV shows.
It also updates API paths to reference the new UserSettings schema.
- Fixes #XXXX
=> fix(api): add missing user settings' api docs

jellyseerr-api.yml, server/api/themoviedb/index.ts, server/job/blacklistedTagsProcessor.ts, server/routes/discover.ts, server/routes/index.ts, src/components/BlacklistedTagsBadge/index.tsx, src/components/BlacklistedTagsSelector/index.tsx, src/components/Discover/CreateSlider/index.tsx, src/components/Selector/index.tsx, src/components/Settings/OverrideRule/OverrideRuleTiles.tsx
This PR fixes an issue where tag-based blacklisting would break if a previously valid TMDB keyword became invalid, causing the settings page to crash and jobs to fail with 404 errors.
API routes now return proper 404 statuses for invalid keywords. Keyword validity is checked before processing, and invalid keywords are automatically removed from settings.
- Fixes #1814
=> fix(blacklist): handle invalid keywords gracefully

jellyseerr-api.yml
Fixes validation error when sending null username values.
- Fixes #1834
=> fix(api): make username field nullable in UserSettings API schema

server/api/plextv.ts
This PR updates the Plex watchlist base URL to the new endpoint, replacing the deprecated one.
- Fixes #XXXX
=> fix(api): update Plex Watchlist URL

src/components/Common/SettingsTabs/index.tsx, src/components/PWAHeader/index.tsx
Removed the deprecated `<meta name="apple-mobile-web-app-capable" content="yes" />` tag from the PWAHeader component, as recommended by updated browser standards. Kept the modern `<meta name="mobile-web-app-capable" content="yes" />` tag to ensure proper PWA support and resolve browser console warnings. No functional changes to the component.
Added id="tabs" attribute to the `<select>` element so that the associated `<label htmlFor="tabs">` correctly links to it.
This resolves the accessibility error:
“Incorrect use of `<label for=FORM_ELEMENT>` — label’s for attribute doesn't match any element id”.
Without this fix, assistive technologies and browser autofill might not work properly.
- Fixes #XXXX
=> fix: remove console warning

server/routes/issue.ts, src/components/IssueList/IssueItem/index.tsx, src/i18n/locale/en.json
This PR adds a description preview to the issues list page, allowing users to quickly view issue details without navigating to individual issue pages.
- Fixes #1868
=> feat(issue): add issue description preview

server/api/tvdb/index.ts
The previous validation condition incorrectly excluded seasons with number 0, preventing the display of special episodes which are typically classified as "season 0" in TVDB.
- Fixes #XXXX
=> fix(tvdb): display of special episodes (season 0) for TVDB

.prettierignore
Fixes an error with Prettier ignoring the `sw.js` file in the public folder.
=> fix(prettier): include sw.js file in .prettierignore

jellyseerr-api.yml, server/api/themoviedb/index.ts, server/routes/discover.ts, src/components/Discover/FilterSlideover/index.tsx, src/components/Discover/constants.ts, src/i18n/locale/en.json
This PR adds keyword exclusion functionality to the discover filter system.
- Fixes #350
=> feat(api): add excludeKeywords parameter to discovery queries

package.json, pnpm-lock.yaml, server/index.ts
Previously `dnsCache` was being initialized even if it was disabled because the previous check was always returning truthy.
In addition, this PR fixes `dnsCache` not respecting the `forceIpv4` flag (this is fixed in the package itself)
- Fixes #1857
=> fix(dnscaching): check dnsCache before init & support forceipv4 with caching

jellyseerr-api.yml, server/routes/request.ts
This PR updates the `/api/v1/request/count` endpoint by adding a new completed field, which shows how many requests have been fully fulfilled.
Previously, the endpoint only returned `available: 0`, even though the media had already become available. That’s because requests are automatically marked as `COMPLETED` once the media is available, skipping the `AVAILABLE` state. This caused a mismatch - while the web UI correctly showed fulfilled requests, the API didn’t reflect that.
- Fixes #1817
#1735
=> feat(api): add completed count to request count API

server/api/animelist.ts, server/api/jellyfin.ts, server/lib/scanners/jellyfin/index.ts
This PR adds AniDB support in the Jellyfin scanner.
The AniDB ID is used only if there's no other provider id available to ensure it doesn't change the way it works now with TMDB/TVDB.
In some cases it doesn't work correctly, for example if the show is splitted in multiple season while on anidb it's a single season.
I know it's not optimal, but these are quite rare cases and i think it's better than nothing.
=> feat: add anidb support to jellyfin scanner

.github/workflows/support.yml
fixed the gh -R issue
This should sort out the issue with it not knowing which the repo it’s in without checkout.
if this release fails we should roll back to the previous commit from before the upgrade of all work flows for this file only.
=> ci: fix the gh -R issue in support.yml 

.github/renovate/docker.json5, .github/renovate/helm.json5
chore: update renovate bot logic to remove pin from compose files and charts
=> chore: update renovate bot logic to remove pin from compose files and charts
