seerr-team/seerr

src/components/Settings/SettingsJobsCache/index.tsx
src/i18n/locale/ca.json
src/i18n/locale/de.json
src/i18n/locale/el.json
src/i18n/locale/en.json
src/i18n/locale/es.json
src/i18n/locale/fr.json
src/i18n/locale/hu.json
src/i18n/locale/it.json
src/i18n/locale/nb_NO.json
src/i18n/locale/nl.json
src/i18n/locale/pt_BR.json
src/i18n/locale/pt_PT.json
src/i18n/locale/sv.json
src/i18n/locale/zh_Hant.json

Replaced unknown job with jellyfin in jobsandcache
Added the translations to reflect the fix in all the locales

fix: replaced Unkown job with jellyfin in jobsandcache

---

package.json

update tags to fallenbagel/jellyseerr and the branch from master to main in the release section

update tags and the branch to jellyseerr

---

src/components/IssueList/IssueItem/index.tsx
src/components/Layout/UserDropdown/index.tsx
src/components/RequestCard/index.tsx
src/components/RequestList/RequestItem/index.tsx

Reverts Fallenbagel/jellyseerr#104. The changes were implemented upstream: https://github.com/sct/overseerr/pull/2782

Revert "Fix non-square profile pictures being squished"

---

README.md

Updates readme to add manual install steps and aur package info
- Fixes #XXXX

Add manual install steps and aur package info

---

README.md

fix aur url

---

next.config.js
src/components/IssueDetails/index.tsx
src/components/Login/JellyfinLogin.tsx
src/components/MovieDetails/index.tsx
src/components/Settings/SettingsJellyfin.tsx
src/components/Settings/SettingsLayout.tsx
src/components/Settings/SettingsUsers/index.tsx
src/components/Setup/SetupLogin.tsx
src/components/TvDetails/index.tsx
src/components/UserList/JellyfinImportModal.tsx
src/components/UserList/index.tsx
src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx

Fix emby ui elements not reflecting the emby env variable set during runtime
- Fixes #98

fix(ui): fix emby ui elements not reflecting the env variable

---

src/components/Settings/SettingsAbout/index.tsx
src/components/Settings/SettingsJobsCache/index.tsx
src/components/Settings/SettingsLayout.tsx

This will make things more clear until we support running multiple modes at the same time.

Hide Overseerr settings when running in Jellyfin/Emby mode

---

server/api/jellyfin.ts

Sorry in advance, fixing errors introduced in previous PR.

fix(jellyfin): sync errors

---

src/components/Settings/SettingsJellyfin.tsx

Fix text for manual library scan

Fix text for manual library scan

---

.github/workflows/release.yml

add yarn dependencies to workflow

add yarn dependencies

---

cypress.config.ts

Change cypress projectId to jellyseerr's project id

test(cypress): change cypress projectId

---

.github/workflows/release.yml
.github/workflows/snap.yaml
snap/snapcraft.yaml

Prepare for jellyseerr snap builds

Prepare snap builds [skip ci]

---

server/job/jellyfinsync/index.ts

Related with PR https://github.com/Fallenbagel/jellyseerr/pull/444, missed the 4k. Apologies.

fix: repeat notifications for available 4k media

---

docker-compose.yml

named service inside docker-compose.yml

---

README.md

Add more detailed installation instructions.
- Fixes #428

Add more detailed installation instructions

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement.yml

Rename template usages of "Overseerr" to "Jellyseerr"

update .github folder templates

---

server/job/schedule.ts
server/lib/scanners/jellyfin/index.ts
server/routes/settings/index.ts

refactor: jellyfin scan jobs moved from server/jobs to server/libs/scanners

---

src/i18n/locale/de.json

fix german translation for "components.Discover.FilterSlideover.tmdbuservotecount"

fix: translation de.json

---

README.md

I didn't know about overseerr and discovered this by accident, so linking to the upstream project helps understand what this is for

Link related projects in README.md

---

.github/workflows/preview.yml

Adds arm builds for preview tags, allowing people that use ARM to test preview builds.
I need this to test #628

ci(preview): added arm support for preview tags

---

README.md

Just a simple typo fix on the README.md file.
- Fixes #XXXX

fix(readme): fixed a typo

---

overseerr-api.yml

- fixes errors in `overseerr-api.yml`

Fix overseerr-api.yml

---

.github/FUNDING.yml

just updating the funding link as github sponsor link was added by mistake.
- Fixes #XXXX

chore: replace github sponsor with buymeacoffee

---

.github/workflows/snap.yaml

style: ran prettier on snap yaml file

---

server/api/jellyfin.ts

adds fallback to authenticate without headers to ensure and improve resilience across different browsers and client configurations.
- Fixes #XXXX

fix(auth): improve login resilience with headerless fallback authention

---

README.md

Add docs for building Jellyseerr from source for latest version and development version
- Fixes #XXXX

docs: add docs for building Jellyseerr from source for latest version and development version

---

.github/workflows/docs-deploy.yml
gen-docs/docusaurus.config.ts

- Increases the download-artifact version
- Disables trailing slash
- Let docusaurus use the default deploy branch
- Fixes #XXXX

ci: attempt to fix docs deployment

---

.github/PULL_REQUEST_TEMPLATE.md

docs: update to the latest build/i18n extract instructions [skip ci]

---

src/components/Settings/SettingsAbout/index.tsx

Changes the docs link to jellyseerr docs link in about page
- Fixes #XXXX

refactor: changes the docs link to jellyseerr docs link in about page

---

docs/getting-started/docker.mdx

Adds a more detailed instruction on how to change the JELLYFIN_TYPE env variable for emby
- Fixes #XXXX

docs: add better env variable instructions

---

src/assets/services/plex.svg

Update the Plex logo from its old version to the new one.
before:
after:

feat: update Plex logo

---

server/utils/rateLimit.ts

This PR fixes the rateLimit function that was allowing X parallel requests instead of limiting to X requests per second.

fix: rewrite the rate limit utility

---

src/components/MovieDetails/index.tsx

Fix errors coming from the merge of develop and #781 
- Fixes #XXXX

fix: rewrite request from axios to Fetch

---

src/components/UserList/JellyfinImportModal.tsx

Currently import button sometimes shows already imported users and this would break it if an admin tries to import an already imported user.
- Fixes #XXXX

fix: update the filter removing existing users from Jellyfin import modal

---

server/lib/settings/migrations/0003_emby_media_server_type.ts

Just a little clean up. Removes console log and renames the migration in chronological order of pr merge.
- Fixes #XXXX

chore(migrations): proper rename & clean up of media server type migration

---

README.md

Updates the translate badge link
- Fixes #XXXX

docs(readme): update the translate badge

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/enhancement.yml

Fix the defaults labels added while creating an issue.
- Fixes #XXXX

chore(issuetemplate): update defaults labels of GitHub issues

---

overseerr-api.yml
server/index.ts
server/routes/index.ts
server/utils/appDataVolume.ts

feat: add a warning if permissions are missing from config folder

---

server/api/jellyfin.ts
server/api/plexapi.ts
server/lib/scanners/plex/index.ts
server/lib/settings/index.ts
server/lib/settings/migrations/0001_migrate_hostname.ts
server/lib/settings/migrations/0002_migrate_apitokens.ts
server/lib/settings/migrator.ts
server/routes/auth.ts
server/routes/settings/index.ts
server/routes/settings/notifications.ts
server/routes/settings/radarr.ts
server/routes/settings/sonarr.ts

This PR switches from synchronous operations with the 'fs' module to asynchronous operations with the 'fs/promises' module. It also corrects a small error with hostname migration.
- Fixes #XXXX

fix: use fs/promises for settings

---

server/api/plexapi.ts
server/index.ts
server/lib/scanners/plex/index.ts
server/lib/settings/index.ts
server/lib/settings/migrations/0001_migrate_hostname.ts
server/lib/settings/migrator.ts
server/routes/auth.ts
server/routes/settings/index.ts
server/routes/settings/notifications.ts
server/routes/settings/radarr.ts
server/routes/settings/sonarr.ts
server/utils/customProxyAgent.ts
server/utils/restartFlag.ts
src/components/Settings/SettingsMain/index.tsx

This PR adds more options to the proxy setting, like username/password authentication, bypass list
of domains and bypass local addresses. The UX is taken from *arrs.
- Fixes https://github.com/Fallenbagel/jellyseerr/issues/1025#issuecomment-2439653494

feat: add bypass list, bypass local addresses and username/password to proxy setting

---

server/routes/auth.ts

This PR fixes a bug where the setup process was stuck if any error occurred after the first setup.
Instead of just checking if an admin user exists in database, this PR will also check if the settings are properly set up, and if so edit the admin user according to the new settings provided during the 2nd setup.
Steps to reproduce:
- Do the whole setup process
- Stop Jellyseerr
- Delete settings.json
- The setup page appears again but you can't setup Jellyseerr anymore.
- Fixes #XXXX

fix: resolve error when setup on second attempt

---

CONTRIBUTING.md

Fix the install command inside the CONTRIBUTING docs.
- Fixes #XXXX

docs: fix pnpm install command

---

src/context/LanguageContext.tsx
src/pages/_app.tsx

Description
Jellyseerr's Turkish translation has been completed via weblate and the necessary fields have been added to the "LanguageContext" and "_app.tsx" files.
To-Dos
Successful build pnpm build
Translation keys pnpm i18n:extract

Turkish language added 

---

CONTRIBUTING.md

docs: add explainations to generate migrations with TypeORM

---

cypress/config/settings.cypress.json
overseerr-api.yml
server/entity/MediaRequest.ts
server/interfaces/api/settingsInterfaces.ts
server/lib/scanners/plex/index.ts
server/lib/scanners/sonarr/index.ts
server/lib/settings/index.ts
src/components/RequestCard/index.tsx
src/components/RequestList/RequestItem/index.tsx
src/components/RequestModal/TvRequestModal.tsx
src/components/Settings/SettingsMain/index.tsx
src/components/TvDetails/index.tsx
src/context/SettingsContext.tsx
src/i18n/locale/en.json
src/pages/_app.tsx

This PR adds a separate setting for special episodes and disables them by default, to avoid unwanted library status updates.

feat: add a setting for special episodes

---

src/components/Settings/SettingsMain/index.tsx

Fixes the http-proxy settings styling for mobile design when active.
Before:
**After:**
- Fixes #XXXX

style(http-proxy): fix margin for responsive design

---

src/components/Settings/SettingsMain/index.tsx

**We don't talk about this.**
Fixes the position of the save button in settings > General.
- Fixes #XXXX

refactor(settings): fix save button position

---

server/entity/MediaRequest.ts

Updated the logic of override rules to be applied during the request phase and not during send-to-arr phase. In addition, override rules will only apply for non-admin/non-auto-approve users.
Override rule logic has been changed to the following:
- Admins and users with auto-approve permissions bypass override rules, retaining their flexibility to choose their options.
- Other users have their requests automatically adjusted based on applicable override rules prior to approval.
- Fixes #1195

fix(overriderules): apply override rules during request only for non-admin/non-auto-approve users

---

server/entity/MediaRequest.ts

Forgot to apply override rules to tv shows on #1197
- Fixes #1195

fix(overriderules): apply override rules to tv shows during request

---

server/entity/MediaRequest.ts
server/lib/scanners/sonarr/index.ts
src/components/RequestModal/TvRequestModal.tsx
src/components/TvDetails/index.tsx

Some typos were introduced by #1193, enableSpecialEpisodes and partialRequestsEnabled were mixed up.
- Fixes #1208

fix: correct typos for the special episodes setting

---

src/components/RequestList/index.tsx

Previously the styling was a little off. This should align the styling with the other icons (see screenshots).
**Previously:**
**After:**
(on hover the sort icon will be white and will have the same button color as the rest of the application)
- Fixes #XXXX

style(request-list): consistent styling of sort button with the rest

---

server/entity/MediaRequest.ts

This change optimises the media updates to avoid unneccessary lifecycle hook executions which results in potential recursion for POSTGRESQL compatibility. This should prevent an issue where after a TV request, the tv request would get sent to sonarr and notification for it would get sent over and over and over again.
This is the only fix I found to avoid the infinite recursions when using POSTGRESQL db
- Fixes #XXXX

fix: optimize media status update to avoid lifecycle hook triggers

---

src/components/Settings/SettingsPlex.tsx
src/components/Setup/index.tsx

Fixes step 3 not letting you continue for plex and the scroll-to-top issue when continue button is clicked
- Fixes #XXXX

fix(setup): plex library setting validation

---

src/components/Setup/index.tsx

Fixes some linting issues introduced by #1233
- Fixes #XXXX

refactor: resolve missing dependency warning for `validateLibraries` in useEffect

---

docs/extending-jellyseerr/database-config.mdx
docs/getting-started/buildfromsource.mdx
docs/getting-started/docker.mdx
docs/getting-started/nixpkg.mdx
gen-docs/src/components/JellyseerrVersion/index.tsx
server/datasource.ts

This adds an env variable to accept unix connections for postgres. Documentation have been updated to reflect this.
- Fixes #XXXX

refactor(postgres): add postgres socket

---

README.md
docs/README.md

Just updates the docs to make the available features and what jellyseerr is more clear (as there has been misconceptions that jellyseerr only supports jellyfin).
- Fixes #XXXX

docs: update the current list of features we offer

---

.github/workflows/release.yml
package.json

This PR ensures that a `latest` tag is created for ghcr.io container image like the Docker Hub one.
- Fixes #736

feat: Add latest tag to ghcr container image

---

.github/workflows/ci.yml

Tags cant container `/` so this should sanitise them.
- Fixes #XXXX

ci: sanitise container tag

---

charts/jellyseerr-chart/Chart.yaml
charts/jellyseerr-chart/README.md
charts/jellyseerr-chart/templates/deployment.yaml
charts/jellyseerr-chart/values.yaml

Add possibility to pass volumes and volume mounts
- Fixes #1285

feat(helm): Add possibility to pass volumes and volume mounts

---

charts/jellyseerr-chart/Chart.yaml
charts/jellyseerr-chart/README.md

fix(helm): no change, fixing OCI manifest corruption
- Fixes #XXXX

fix(helm): no change, fixing OCI manifest corruption

---

Dockerfile

Removes charts, docs, and gen-docs from the final docker image.
- Fixes #1313

build: remove unnecessary files from final docker image

---

docs/getting-started/docker.mdx

in newer versions of docker, the location of Docker volumes has now changed. 
See: https://stackoverflow.com/a/64418064

docs: update docker volume location in windows

---

public/robots.txt

This PR adds a `robots.txt` file to prevent crawlers to index the website
- Fixes #1323

feat: add a robots.txt file

---

src/components/MovieDetails/index.tsx
src/components/TvDetails/index.tsx

This corrects spelling errors in function names, No other changes.
-
-

fix: correct typo in movie/tv details page

---

server/entity/MediaRequest.ts

This is related to #1218. This should fix more typeorm lifcycle trigger issues
There should be a preview available as the tag: `preview-lifecycle-fix`
- Fixes #513
- Fixes https://discordapp.com/channels/952656177924300932/1338807768555192320

fix(mediarequest): optimise more typeorm lifecycle triggers

---

server/api/jellyfin.ts

Fix Jellyfin/Emby item retrieval to work properly with api tokens by using user-independent item endpoints. This will resolve the issue where disabled libraries for jellyseerr owner's would fail to scan even when we migrated to API tokens due to using the user-dependent item view endpoints.
This PR can be tested using `preview-user-independent-items`
- Fixes #XXXX

fix(api): make item endpoints user-independent

---

src/components/Settings/SettingsServices.tsx

The condition was incorrectly written.
- Fixes #1417

fix(overriderules): correct disabled condition for override rule creation

---

charts/jellyseerr-chart/Chart.yaml
charts/jellyseerr-chart/README.md

feat(helm): upgrade jellyseerr to 2.4.0

---

src/components/Login/JellyfinLogin.tsx
src/components/Login/LocalLogin.tsx

Should be all to get this working again.
- Fixes #1452

fix(auth): Bitwarden autofill fix on local/Jellyfin login

---

charts/jellyseerr-chart/Chart.yaml
charts/jellyseerr-chart/README.md

upgrade jellyseerr app to 2.5.0

chore(helm): upgrade jellyseerr app to 2.5.0

---

docs/troubleshooting.mdx

This adds more troubleshooting steps to the troubleshooting page.
- Fixes #XXXX

docs: add more troubleshooting steps

---

server/lib/availabilitySync.ts

Ensure media availability updates correctly for shows marked as UNKNOWN and yet having AVAILABLE or PARTIALLY_AVAILABLE seasons

fix(job): resolve edge case issue with season availability updates

---

CONTRIBUTING.md

Add contributing guidelines for helm chart

docs(helm): add contributing guidelines for helm chart

---

charts/jellyseerr-chart/Chart.yaml
charts/jellyseerr-chart/README.md
charts/jellyseerr-chart/templates/persistentvolumeclaim.yaml

Annotations are not being added to the PVC. This PR fixes that.

fix(helm): apply annotations to pvc

---

CONTRIBUTING.md
src/components/Settings/OverrideRule/OverrideRuleTiles.tsx

This fixes some linting and formatting issues currently present.
- Fixes #XXXX

chore: fix linting and formatting issues

---

charts/jellyseerr-chart/Chart.yaml
charts/jellyseerr-chart/README.md

chore(helm): bump jellyseerr to 2.5.2

chore(helm): bump jellyseerr to 2.5.2

---

server/api/themoviedb/index.ts

feat(api): set tmdb api query's default language based on locale setting

---

jellyseerr-api.yml
server/routes/request.ts
src/components/RequestList/index.tsx

This PR adds media type filtering to the requests list, allowing filtering by movies, series, or all.
- Satisfies one of #497

feat(requestlist): add requests list media type filtering

---

server/entity/Media.ts

Pull changes from upstream/develop

chore: merge upstream

---

docs/troubleshooting.mdx

docs: add a troubleshooting section for lost admin access

---

charts/jellyseerr-chart/Chart.yaml
charts/jellyseerr-chart/README.md

chore(helm): bump jellyseerr to 2.7.0

---

server/api/externalapi.ts
server/api/tautulli.ts
server/lib/imageproxy.ts
server/utils/customProxyAgent.ts

This PR fixes the proxy settings not working on every requests since the migration to Axios. It also fixes the authentication issue when authenticating to the proxy.
- Fixes #1730

fix(proxy): apply all proxy settings to Axios

---

docs/getting-started/docker.mdx

following https://github.com/fallenbagel/jellyseerr/pull/1726 (sad mistake :clown_face:)
I've removed ghcr.io as default until you are okay with it :)

docs(docker): add healthcheck to documentation

---

docs/using-jellyseerr/plex/_category_.json
docs/using-jellyseerr/plex/index.md
docs/using-jellyseerr/plex/watchlist-auto-request.md

Adding some docs related to plex's integration.
- Fixes #XXXX

docs(plex): add some Plex integration related documentation

---

charts/jellyseerr-chart/Chart.yaml
charts/jellyseerr-chart/README.md

chore(helm): bump jellyseerr to 2.7.1

---

server/subscriber/MediaRequestSubscriber.ts

This PR fixes a bug where `MEDIA_AVAILABLE` notifications would sometimes fail because of stale entity data. We now use TypeORM’s event manager to grab the fresh media state inside the transaction, which seems to solve it reliably.
- Fixes #1771

fix(MediaRequestSubscriber): use event manager to get fresh media state for MEDIA_AVAILABLE notifications

---

charts/jellyseerr-chart/Chart.yaml
charts/jellyseerr-chart/README.md

chore(helm): bump jellyseerr to 2.7.3

---

src/components/RequestBlock/index.tsx

This PR adds user's respective avatar in the RequestBlock's component.
- Fixes #965

feat(requests): add user's avatar next to Requested/Last Modified by icon

---

.github/workflows/ci.yml
.github/workflows/cypress.yml
.github/workflows/docs-deploy.yml
.github/workflows/release.yml
.github/workflows/test-docs-deploy.yml

ci: remove the with step from the pnpm setup steps

ci: remove the with step from the pnpm setup steps

---

Dockerfile
Dockerfile.local

build: fix pnpm version in Dockerfile

---

.github/PULL_REQUEST_TEMPLATE.md

Wrong branch was linked in pr template.

docs: update link to AI assistance policy in PR template

---

gen-docs/blog/2025-09-29-introducing-jellyseerr-blog.md
gen-docs/blog/authors.yml
gen-docs/docusaurus.config.ts
gen-docs/package.json
gen-docs/pnpm-lock.yaml

This enables blog with a simple welcome to the blog post.
This PR also updates docusaurus to the latest version to make use of the authors page.
- Fixes #XXXX

docs(blog): implement blog

---

compose.postgres.yaml

Same as https://github.com/fallenbagel/jellyseerr/pull/1073

chore: migrate compose postgres to compose v2

---

.github/workflows/cypress.yml

ci: updated cypress paths to stop noisy runs

ci: updated cypress paths to stop noisy runs

---

.github/workflows/docs-link-check.yml
.github/workflows/trivy-scan.yml

- Fix trivy tag
- Reformat some workflows

chore(renovate): fix trivy action tag

---

.github/workflows/ci.yml
.github/workflows/release.yml

Description:
ci(ci.yml,release.yml): removes the need for 3rd party actions
This will stop the need to use `sarisia/actions-status-discord` &
`technote-space/workflow-conclusion-action`

ci(ci.yml,release.yml): removes the need for 3rd party actions

---

.github/workflows/ci.yml
.github/workflows/helm.yml
.github/workflows/lint-helm-charts.yml

Sort out digest of node and docker image hash for linting helm

ci: updating digests re pr-1998
